### ISSUE TITLE
Refactor Add Genre

### ISSUE THREAD

**Issue by bullitbd** [andyjac/hinton#141]
needs to populate and re-pull list

**Comment by andyjac** [comment]
It should already be doing this.

**Comment by bullitbd** [comment]
yes... but doesn't add to list until rest saved - not a biggie.

**Comment by andyjac** [comment]
Right, but that's the way it should be imo. The genre shouldn't be in the drop down until she's decided to use it with a restaurant for the first time, because only then is the genre actually in the db.

**Comment by bullitbd** [comment]
True... but there's typically another way to thoughtfully put genres in -
rather than willy-nilly guessing at the entry time - that's what a
dictionary is for - to look up consistent entries.  agree the restaurant
add screen isn't the appropriate place for that - just trying to shoehorn
in the functionality.

Bob Day
Rialto Advisors
(206) 323-9664
LinkedIn <http://linkedin.com/in/daybob>
